### ISSUE TITLE
PackageManagement 1.4.1 demands multi-factor auth when providing a PAT

### ISSUE THREAD

**Issue by Launcelot555** [OneGet/oneget#460]
### Environment Overview
Hosted VS2017 Azure DevOps Agent
### Issue Overview
When providing a PAT and PSCredential object to Register-PSRepository in Azure DevOps using PackageManagement 1.4.1, two-factor authentication is required. 
This is to register an Azure DevOps Artifact Repository.
### Expected Behavior
In previous versions of PackageManagement, providing a PAT did not require multi-factor authentication. 
### Actual Behavior
![image](https://user-images.githubusercontent.com/1081487/58985626-a4b6e200-8790-11e9-8c5e-1c56abc177ca.png)

**Comment by markekraus** [comment]
Looks like this regression was introduced OneGet/NuGetProvider#56 wherein provided credentials appear to be disregarded.

**Comment by alerickson** [comment]
Could you share what your -verbose -debug output is?

**Comment by markekraus** [comment]
What you see is the verbose output.


You can repro this by doing the following:

1. Create a new Azure DevOps Artifact Feed
1. Generate a PAT with read access to packagemanagement
1. Run the following

```powershell
$PAT = Read-Host -Prompt PAT -AsSecureString
$AzDoOrg = Read-Host -Prompt 'Azure DevOps Organization'
$FeedName = Read-Host -Prompt 'Azure DevOps Artifact Feed Name'

$Credentials = [pscredential]::new('azdo',$PAT)
$FeedUri = 'https://pkgs.dev.azure.com/{0}/_packaging/{1}/nuget/v2/' -f $AzDoOrg, $FeedName

Register-PSRepository -Name $FeedName -SourceLocation $FeedUri -Credential $Credentials  -InstallationPolicy Trusted -PackageManagementProvider Nuget -PublishLocation $FeedUri -Verbose -Debug
```

Works fine in PackageManagement 1.4, but in 1.4.1 it prompts like this:

```none
[Minimal] [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/*********/_packaging/*****/nuget/v2/
[Minimal] [CredentialProvider]To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code *********** to authenticate.
```

**Comment by SydneyhSmith** [comment]
Thanks for all the feedback, and patience--we've released updates to both PackageManagement and PowerShellGet yesterday to fix this and I wanted to see if that had resolved the issues you are facing? 

CC: @alerickson

**Comment by markekraus** [comment]
@SydneyhSmith and @alerickson I have confirmed that the problem persists with PM 1.4.2 and PSGet 2.1.5. The same repro code above still produces the same result.

**Comment by alerickson** [comment]
Thanks for letting us know!  I’ll look into this today.  This integration’s been a bit hairy so thanks for bearing with us

**Comment by alerickson** [comment]
@Launcelot555  @markekraus  I just published [PowerShellGet](https://www.poshtestgallery.com/packages/PowerShellGet/2.2) and [PackageManagement](https://www.poshtestgallery.com/packages/PackageManagement/1.4.3) to our int gallery.  Please feel free to test these out and see if behavior is working appropriately.  The credential provider should only be prompted if the -credential parameter is not passed in

**Comment by SydneyhSmith** [comment]
To get these modules from the int gallery run: 
` Register-PSRepository -Name PoshTestGallery -SourceLocation https://www.poshtestgallery.com/api/v2`
`Install-Module PowerShellGet, PackageManagement -Repository PoshTestGallery -Force`

**Comment by markekraus** [comment]
@alerickson @SydneyhSmith the problem appears to be resolved in PM 1.4.3 and PSGet 2.2
