### ISSUE TITLE
Certificate has expired for https://onegetcdn.azureedge.net/

### ISSUE THREAD

**Issue by HamzaBA26** [OneGet/oneget#554]
same issue as a few months ago 

https://github.com/OneGet/oneget/issues/553

<img width="563" height="658" alt="Image" src="https://github.com/user-attachments/assets/d05da25e-2665-47b4-9ded-7ce2672e5f07" />

**Comment by FingerlessGlov3s** [comment]
Got the same issue here as well, causing issues with device deployments.

**Comment by mmcdermo2** [comment]
Same here, preventing us from running a bunch of our test pipelines

**Comment by lmerola227** [comment]
here, waiting because I need to download some modules

**Comment by Jorvik1904** [comment]
Same here (in UK)

**Comment by bartAtHome** [comment]
Up.

**Comment by david-heath-accurx** [comment]
+1

**Comment by joshuadenson** [comment]
Adding a comment for visibility. 
Issues is still present in the EU, you can bypass the cert checks but that of course carries risk.

**Comment by mivalsten** [comment]
tagging @alerickson and @anamnavi as you were the one that fixed that last time.

**Comment by SelfMan** [comment]
Confirmed.
Issue is causing problems with NuGet installations.

**Comment by nikitallo** [comment]
Also confirmed. It affects our auto tests

**Comment by hliebig-zeiss** [comment]
Same here in EU for automated build and test tasks

**Comment by Zeromatterhorn** [comment]
same here, affects a huge rollout... again 😆

**Comment by straeb** [comment]
Jesus, how could such thing be a reoccurring issue in 2025...

**Comment by Xony7997** [comment]
Same here. Rebuilding user devices and have 3 wiped and stuck 🤔

**Comment by PaulFleming438765** [comment]
+1 here.  Unable to download nuget for autopilot builds.

**Comment by istolpov** [comment]
I'm bumping this since no response from Microsoft and last comment is half an hour ago.
This is a P0 level incident, Microsoft. Page your operations.

-----
P.S. I was lucky enough not to have anything suddenly broken on no change. Instead, I was debugging my powershell VM bootstrap scripts for several hours thinking I am an idiot and do something wrong.

**Comment by MrShark** [comment]
Found this blogpost from June, that documents how to deactivate certificate checks.
Proceed with caution.
https://patchmypc.com/blog/no-match-was-found-while-installing-the-nuget-packageprovider/

Also note that  azureedge.net was part of the edg.io bankruptcy, so Microsoft might not have direct control over the cert.
https://learn.microsoft.com/en-gb/azure/frontdoor/migrate-cdn-to-front-door

**Comment by rajavardhanl** [comment]
Same here. Not working

**Comment by nimor109** [comment]
Same's happening here preventing production deployment. Just commenting to add weight to the post.

**Comment by alibadra** [comment]
Same issue here with device deployment, affecting three regions: Europe, Africa, and Asia

**Comment by stdunning** [comment]
If only there were a way to prevent this recurring incident.  If you search the web you find a few of this exact issue that no one has bothered to prevent from happening again and again.

**Comment by anthonysomerset** [comment]
> Found this blogpost from June, that documents how to deactivate certificate checks. Proceed with caution. https://patchmypc.com/blog/no-match-was-found-while-installing-the-nuget-packageprovider/
> 
> Also note that azureedge.net was part of the edg.io bankruptcy, so Microsoft might not have direct control over the cert. https://learn.microsoft.com/en-gb/azure/frontdoor/migrate-cdn-to-front-door

MSFT has full controll of azureedge.net DNS - its on their NS so they should have direct control over this. this also appears to be fronting through to akamai cdn based on basic DNS lookups also

```
$ dig onegetcdn.azureedge.net

; <<>> DiG 9.10.6 <<>> onegetcdn.azureedge.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2369
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;onegetcdn.azureedge.net.	IN	A

;; ANSWER SECTION:
onegetcdn.azureedge.net. 43	IN	CNAME	tm-onegetcdn.trafficmanager.net.
tm-onegetcdn.trafficmanager.net. 2 IN	CNAME	cdn.oneget.org.edgesuite.net.
cdn.oneget.org.edgesuite.net. 20940 IN	CNAME	a155.dscd.akamai.net.
a155.dscd.akamai.net.	20	IN	A	2.18.190.105
a155.dscd.akamai.net.	20	IN	A	2.18.190.165
```

**Comment by benfrussell** [comment]
Affecting Canada - impacting production services.

**Comment by Screenday** [comment]
Same issue here with device deployment from Switzerland. :/

**Comment by simgarnordlo** [comment]
Same issue here in Sweden

**Comment by ceciliasharp** [comment]
Big impact on our nightly testing-pipelines, please prioritise.

**Comment by jonathan-knights** [comment]
Same issue here in UK.

**Comment by kfdl** [comment]
same here in France

**Comment by ibeerens** [comment]
I have the same problem when deploying images :-(

**Comment by akukalles** [comment]
This is blocking our win11 project🫠

**Comment by billypurdue** [comment]
uuuuugggghhhhhhhh

**Comment by radkujawa** [comment]
same here

**Comment by HOOTYMCB00B** [comment]
same here in Guernsey, been causing me issues for an hour trying to get nuget for get-windowsautopilotinfo.

**Comment by Brad-Hand** [comment]
Can confirm here as well. In the middle of standing up AutoPilot and trying to demo it to my team and now I can't harvest the hashes because it can't download NuGet. Showing same cert expired as OP.

**Comment by HOOTYMCB00B** [comment]
fixed, just tried it

**Comment by joshuadenson** [comment]
It doesn't look fixed from my side. Still seeing the old cert. Tried on a few clients in differing locations.

<img width="622" height="722" alt="Image" src="https://github.com/user-attachments/assets/df314691-34fa-4ec3-94ec-0cd9101fff5d" />

**Comment by ImMattAsh** [comment]
not fixed for me either (I'm in the US, fwiw)

**Comment by SelfMan** [comment]
The Cert for https://cdn.oneget.org/providers/nuget-2.8.5.208.package.swidtag is now OK.
The definition points to https://cdn.oneget.org/providers/Microsoft.PackageManagement.NuGetProvider-2.8.5.208.dll

and the CDN has a new certificate as well

<img width="758" height="1077" alt="Image" src="https://github.com/user-attachments/assets/ccd07fb3-83c8-452c-a1fa-1b733f3b8079" />

**Comment by alerickson** [comment]
Hi all, this issue is mitigated now.  Our OneGet swidtags started pointing to our old CDN, we mitigated the issue by purging the cache and things seem to be stable.  We're working with our CDN provider to see if there were any changes on their side.

**Comment by SelfMan** [comment]
Thanks for the feedback

**Comment by Brad-Hand** [comment]
> Hi all, this issue is mitigated now. Our OneGet swidtags started pointing to our old CDN, we mitigated the issue by purging the cache and things seem to be stable. We're working with our CDN provider to see if there were any changes on their side.

I have tried to run `Install-Script Get-WindowsAutopilotInfo` for a device and it's still trying to pull NuGet from the onegetcdn.azureedge.net repository which is failing. I've rebooted and flushed DNS. Are there other actions I can perform to force it to refresh and pull from the correct location?

**Comment by alerickson** [comment]
@Brad-Hand could you try again now?  We just tried purging the entire CDN

**Comment by Brad-Hand** [comment]
> [@Brad-Hand](https://github.com/Brad-Hand) could you try again now? We just tried purging the entire CDN

Looks like that did it! I did a reboot and dns flush just in case and it successfully installed NuGet!. Thank you for the quick work!

**Comment by erdembayar** [comment]
@alerickson 

How can I reach you? Alternatively, feel free to message me, I'm with MS internal.

**Comment by lfslsh** [comment]
Whatever was wrong with SSL certs that were valid for 2 years...

**Comment by SelfMan** [comment]
> Whatever was wrong with SSL certs that were valid for 2 years...

It will get worse https://www.digicert.com/blog/tls-certificate-lifetimes-will-officially-reduce-to-47-days

**Comment by matthew-mackarill-veriforce** [comment]
Still expired to me

**Comment by bartAtHome** [comment]
Cert is expired, that is correct but the issue is solved. Read comments above.

**Comment by HamzaBA26** [comment]
Will close as this issue is mitigated now.

**Comment by FingerlessGlov3s** [comment]
Coming up with expired again, both myself and a colleague gets the issue, both different internet connections as well. In the UK, if it's a regional issue now...  When I finished work yesterday it was fine but not it's not working again.

https://onegetcdn.azureedge.net/

**Comment by bartAtHome** [comment]
But why do you need a cert for https://onegetcdn.azureedge.net/?!
I tested the nuget installation just now and it works as expected once the dns entries has been updated.

**Comment by FingerlessGlov3s** [comment]
I don't need a certificate, the server is still giving me the old one. It was ok but it's not returning the old one once again.

curl will also show the issue.

```
curl -4 -v https://onegetcdn.azureedge.net
* Host onegetcdn.azureedge.net:443 was resolved.
* IPv6: (none)
* IPv4: 96.17.207.132, 96.17.207.137
*   Trying 96.17.207.132:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* closing connection #0
curl: (60) SSL certificate problem: certificate has expired
```

<img width="1167" height="836" alt="Image" src="https://github.com/user-attachments/assets/b14ba9a0-fd5c-42d1-829c-b422d227656f" />

**Comment by bartAtHome** [comment]
<img width="548" height="626" alt="Image" src="https://github.com/user-attachments/assets/7e9a5d3a-4182-4e92-808a-ed34c94f3675" />

**Comment by FingerlessGlov3s** [comment]
That's `cdn.oneget.org` not `onegetcdn.azureedge.net`

**Comment by bartAtHome** [comment]
https://github.com/OneGet/oneget/issues/554#issuecomment-3271461615

**Comment by Jorvik1904** [comment]
Did Microsoft even actually acknowledge there was a problem?

**Comment by bdrans** [comment]
Hopefully this helps some people out. I checked versions 2.8.5.201-2.8.5.208 of the Nuget package provider and turns out of those versions only [2.8.5.208](https://cdn.oneget.org/providers/nuget-2.8.5.208.package.swidtag) and [2.8.5.203](https://cdn.oneget.org/providers/nuget-2.8.5.203.package.swidtag) of the Nuget package provider uses `cdn.oneget.org` in its swidtag file. All the other versions I checked instead had their swidtag files still saying `onegetcdn.azureedge.net` (eg. [2.8.5.207](https://cdn.oneget.org/providers/nuget-2.8.5.207.package.swidtag) ). That is where the discrepancy between people saying that need `onegetcdn.azureedge.net` to have a valid cert and others saying you only need `cdn.oneget.org` to be working. Not sure how many other versions of the Nuget Provider are affected or what other providers are effective but hopefully this can give people another starting point to getting it resolved.

**Comment by thecityofguanyu** [comment]
Why was this closed? This is still broken. https://onegetcdn.azureedge.net/ still serves an expired certificate.

**Comment by Brad-Hand** [comment]
> Why was this closed? This is still broken. https://onegetcdn.azureedge.net/ still serves an expired certificate.

Because that CDN is being retired and part of the documented retirement of it from other posts is allowing the cert to expire. They have updated to a new CDN and last I tested it's installing successfully now using their new CDN. 

Are you having issues installing NuGet?

**Comment by thecityofguanyu** [comment]
Yes, `Install-PackageProvider Nuget` still fails due to this issue on Win2019-Server.

```
powershell.exe -command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; Install-PackageProvider Nuget -Force -MinimumVersion 2.8.5.207 -Scope CurrentUser -ForceBootstrap; Install-Module -Name Pester -Force -SkipPublisherCheck -scope CurrentUser }"
WARNING: MSG:UnableToDownload «https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag» «»
WARNING: MSG:UnableToDownload «https://onegetcdn.azureedge.net/providers/psl-1.0.0.210.package.swidtag» «»
WARNING: MSG:UnableToDownload «https://onegetcdn.azureedge.net/providers/ChocolateyPrototype-2.8.5.130.package.swidtag» «»
WARNING: Unable to download from URI 'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag' to ''.
WARNING: Unable to download from URI 'https://onegetcdn.azureedge.net/providers/nugetv2.feed.swidtag' to ''.
WARNING: Unable to download from URI 'https://onegetcdn.azureedge.net/providers/psl.feed.swidtag' to ''.
Install-PackageProvider : No match was found for the specified search criteria for the provider 'Nuget'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At line:1 char:135
+ ... pe]::Tls12; Install-PackageProvider Nuget -Force ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider
```

**Comment by montella1507** [comment]
I can confirm.. It still does not work on Win2019 server., so out software is not installing.

**Comment by montella1507** [comment]
Hi [HamzaBA26](https://github.com/HamzaBA26) 

This is really critical issue - not resolved at all on Win2019. As far as OneGet is used inside Install-Module. Lot of systems have  stopped  working.

**Comment by alerickson** [comment]
@montella1507 is this issue still going on today?  Our CDN provider invalidated everything in the cache yesterday so this should no longer be an issue.  What was previously happening is that our CDN was retrieving outdated cached files.  We had previously tried to purge the cache, and it seems that some of the individual files we purged did indeed properly purge but some that we had thought were purged were not.  Please see this issue for more context: https://github.com/PowerShell/PowerShellGallery/issues/328.

**Comment by montella1507** [comment]
Can confirm it is problem only on Older nuger 

> Yes, `Install-PackageProvider Nuget` still fails due to this issue on Win2019-Server.
> 
> ```
> powershell.exe -command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; Install-PackageProvider Nuget -Force -MinimumVersion 2.8.5.207 -Scope CurrentUser -ForceBootstrap; Install-Module -Name Pester -Force -SkipPublisherCheck -scope CurrentUser }"
> WARNING: MSG:UnableToDownload «https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag» «»
> WARNING: MSG:UnableToDownload «https://onegetcdn.azureedge.net/providers/psl-1.0.0.210.package.swidtag» «»
> WARNING: MSG:UnableToDownload «https://onegetcdn.azureedge.net/providers/ChocolateyPrototype-2.8.5.130.package.swidtag» «»
> WARNING: Unable to download from URI 'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag' to ''.
> WARNING: Unable to download from URI 'https://onegetcdn.azureedge.net/providers/nugetv2.feed.swidtag' to ''.
> WARNING: Unable to download from URI 'https://onegetcdn.azureedge.net/providers/psl.feed.swidtag' to ''.
> Install-PackageProvider : No match was found for the specified search criteria for the provider 'Nuget'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
> At line:1 char:135
> + ... pe]::Tls12; Install-PackageProvider Nuget -Force ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
>     + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider
> ```



I was confused with this... 
It probably does not work with .207

however after installing .208

Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208  -Force

it works.
